-- Supabase schema for the private merch app.
-- Run this in the Supabase SQL editor, then import/migrate your existing rows.

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    ten_danh_muc text not null
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    category_id bigint references public.categories(id) on delete set null,
    ten_san_pham text not null,
    gia numeric(15, 2) not null default 0,
    so_luong integer not null default 1,
    con_hang boolean not null default true,
    da_mua boolean not null default false,
    hinh_san_pham text,
    ten_nhan_vat text,
    shop_ban text not null default '',
    nguoi_mua text,
    ngay_mua date,
    ngay_them timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.products enable row level security;

create policy "Authenticated users can read categories"
on public.categories for select
to authenticated
using (true);

create policy "Authenticated users can write categories"
on public.categories for all
to authenticated
using (true)
with check (true);

create policy "Authenticated users can read products"
on public.products for select
to authenticated
using (true);

create policy "Authenticated users can write products"
on public.products for all
to authenticated
using (true)
with check (true);

insert into storage.buckets (id, name, public)
values
    ('product-images', 'product-images', false),
    ('audio', 'audio', false)
on conflict (id) do nothing;

create policy "Authenticated users can read product images"
on storage.objects for select
to authenticated
using (bucket_id = 'product-images');

create policy "Authenticated users can write product images"
on storage.objects for all
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

create policy "Authenticated users can read audio"
on storage.objects for select
to authenticated
using (bucket_id = 'audio');

create policy "Authenticated users can write audio"
on storage.objects for all
to authenticated
using (bucket_id = 'audio')
with check (bucket_id = 'audio');
